name: Node.js CI

# Trigger GitHub Actions on push or pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-testing:
    runs-on: ubuntu-latest

    strategy:
      # Testing on Node.js 20.x
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Artillery for load testing
      - name: Install Artillery
        run: npm install -g artillery

      # Step 5: Run Artillery Playwright test
      - name: Run Playwright test with Artillery
        run: artillery run load-tests/basic.yml

      # Step 6: Save load test report
      - name: Save load test report
        run: artillery run --output report.json load-tests/basic.yml

      # Step 7: Upload report as an artifact
      - name: Upload load test report
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: report.json
